### ISSUE TITLE
Targeting Linux is broken

### ISSUE THREAD

**Issue by GXTX** [dracc/NevolutionX#126]
Recent changes completely broke targeting Linux. Using NXDK `windows.h` items in a lot of places, etc.

**Comment by abaire** [comment]
If building for Linux is a goal for the project we should also add instructions on how to target Linux and set up a GitHub workflow to make sure it's clear when a PR breaks it. Happy to do so if somebody can point me in the right direction wrt. how to do the build (the README only has instructions for nxdk-based default `make`)

**Comment by GXTX** [comment]
It's meant to be cross-platform yes, which is the reason for the `CMakeLists.txt`.

**Comment by abaire** [comment]
Thanks. I tried to sync back to a working state and it looks like it's been broken since PNG image support was added in `1f131968754e83ddab406d4a21b6bffcee43bd51` (December 9th 2020) - @GXTX can you confirm if you had it working with a more recent commit?

@dracc I can try to get things back to a compilable state w/ the CMakeFile and selective `#ifdef`ing - any objection to also extending the `README` and github workflow to make it more clear that changes should be expected to build on both targets?

**Comment by abaire** [comment]
Fixed and workflow added so it shouldn't break again in the future.

**Comment by GXTX** [comment]
Thanks!
